# Generated by Django 5.1 on 2024-09-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carrito_productos'),
        ('myapp', '0008_alter_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.producto'),
            preserve_default=False,
        ),
    ]
