# Generated by Django 5.1 on 2024-09-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
